; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
lib_deps = 
	bodmer/TFT_eSPI @^2.5.43
	br3ttb/PID @ ^1.2.1
	adafruit/Adafruit MAX31856 library @ ^1.2.7

build_flags = 
    -I./src

    ; TFT_eSPI library settings:
    ; ######################################################
    -D USER_SETUP_LOADED=1
    -include $PROJECT_LIBDEPS_DIR/$PIOENV/TFT_eSPI/User_Setups/Setup42_ILI9341_ESP32.h
    -D DISABLE_ALL_LIBRARY_WARNINGS=1
    ;#######################################################
